name: tests

on:
  workflow_dispatch:


jobs:
   

  windows-msvc:
    runs-on: windows-2019
    name: "Windows (MSVC)"

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            w2c2:
              - 'w2c2/**'
            wasi:
              - 'wasi/**'
      - # if: steps.changes.outputs.w2c2 == 'true'
        name: Build w2c2
        working-directory: ./w2c2
        run: |
          cmake -Bbuild
          cmake --build build
      # TODO: run tests
      - # if: steps.changes.outputs.wasi == 'true'
        name: Build wasi
        working-directory: ./wasi
        run: |
          cmake -Bbuild
          cmake --build build
          ls -l
